### ISSUE TITLE
about keypoint and 

### ISSUE THREAD

**Issue by lexuszhi1990** [xggIoU/centernet_tensorflow_wilderface_voc#1]
here I have two questions:

1. how to get or create tf record?
https://github.com/xggIoU/centernet_tensorflow_wilderface_voc/blob/master/train.py#L47

2. is there any possible to add keypoint predict func?

thx!

**Comment by xggIoU** [comment]
1.These days, I will update the data production after I go home. 
2.In the official original implementation centernet was able to do keypoints detection, which I think is the same thing as object detection, and you can check it out
