### ISSUE TITLE
how to draw heatmap

### ISSUE THREAD

**Issue by chenyanyin** [xggIoU/centernet_tensorflow_wilderface_voc#14]
hello, thank you for sharing the code with us. i want to know how do you draw heatmap as https://github.com/xggIoU/centernet_tensorflow_wilderface_voc/blob/master/display_image/heatmap_modified_box.png, thanks for your reply.

**Comment by xggIoU** [comment]
heatmap_rgb=cv2.merge([heatmap,heatmap,heatmap])
cv2.rectangle(heatmap_rgb, (xmin, ymin), (xmax, ymax), (0, 255, 0), 1)
cv2.imshow('heatmap_box', heatmap_rgb)
cv2.imwrite('heatmap_box.png',heatmap_rgb)

It's easy to understand.

**Comment by chenyanyin** [comment]
got it, thanks~
